#!/usr/bin/env bash

if ! command -v stow &> /dev/null; then
    echo "stow not installed"
    exit 1
fi

./install-base

pushd ~/.cfg > /dev/null
stow -v gestures
stow -v hyprland
stow -v i3
stow -v kitty
stow -v polybar
stow -v sway
stow -v waybar
stow -v xmodmap
popd > /dev/null
