#!/usr/bin/env bash

if ! command -v stow &> /dev/null; then
    echo "stow not installed"
    exit 1
fi

function _stow() {
    echo "Stowing $1"
    \stow "$1"
}

pushd ~/.cfg
_stow fish
_stow gestures
_stow git
_stow i3
_stow kitty
_stow lvim
_stow nushell
_stow nvim
_stow omp
_stow polybar
_stow tmux
_stow vim
_stow vscode
_stow xmodmap
_stow zsh
popd
